# version: "3"

# services:

#   node:
#     image: node:16
#     container_name: desafio-backend
#     tty: true
#     stdin_open: true
#     command: bash
#     restart: always
#     working_dir: /app
#     volumes:
#       - ./:/app
#     depends_on:
#       - db
#     ports:
#       - 3001:3001
#     environment:
#       MYSQL_USER: root
#       MYSQL_PASSWORD: password
#       MYSQL_HOST: db 
#       PORT: '3001'

#   db:
#     container_name: desafio-backend-db
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: 'password'
#     ports:
#       - 3307:3307

# networks:

#   default:

